2019/02/15 22:38:44 [error] 5127#5127: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:39:34 [error] 5127#5127: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:39:35 [error] 5127#5127: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:39:37 [error] 5127#5127: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:40:01 [error] 5186#5186: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:42:39 [error] 5186#5186: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 22:50:15 [error] 5462#5462: *47 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:23:46 [error] 2077#2077: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:23:49 [error] 2077#2077: *24 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:26:00 [error] 3160#3160: *39 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:27:16 [error] 3419#3419: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:28:29 [error] 3419#3419: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:29:21 [error] 3419#3419: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/15 23:29:39 [error] 3419#3419: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:33:29 [error] 904#904: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:33:31 [error] 904#904: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:33:32 [error] 904#904: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:33:33 [error] 904#904: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:52:24 [error] 10405#10405: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 08:52:26 [error] 10405#10405: *28 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 09:05:20 [error] 10754#10754: *59 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 09:07:45 [error] 10834#10834: *67 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 09:14:48 [error] 11019#11019: *86 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 09:14:50 [error] 11019#11019: *86 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/16 09:26:51 [error] 11276#11276: *109 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: backend.test, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "backend.test"
2019/02/28 12:59:17 [error] 876#876: *62 FastCGI sent in stderr: "PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2-debug/src/LogTarget.php on line 85" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /users HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test"
2019/02/28 12:59:23 [error] 876#876: *65 FastCGI sent in stderr: "PHP message: PHP Warning:  touch(): Utime failed: Permission denied in /home/pavel/Geekbrains/adv/vendor/yiisoft/yii2-debug/src/LogTarget.php on line 85" while reading upstream, client: 127.0.0.1, server: backend.test, request: "GET /user HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "backend.test"
